### ISSUE TITLE
Simplified Configuration Layout

### ISSUE THREAD

**Issue by jgjake2** [TaranVH/2nd-keyboard#1]
[I cleaned up the Lua file a little bit.](https://github.com/jgjake2/2nd-keyboard/blob/master/taranLUAmacros.lua) I just threw everything into a standard table using keyboard inputs as the keys, and macro names as values.

Using a table structure will **dramatically** increase keystroke->macro responsiveness.

I haven't tested this at all, and I have to get ready for work, but I'll clean everything else up when I get home ;)

**Comment by csnewman** [comment]
You should consider making this a pull request.

**Comment by maasbello** [comment]
local Key = config[button]
	  if (Key) then

That is faster than type checking. Good job overall!

**Comment by jgjake2** [comment]
> You should consider making this a pull request.
I never tested it, so I wanted to have it validated by others before doing so.

> That is faster than type checking.
True. I was originally doing it to _"idiot-proof"_ call. But, until just now, I never actually read the entire file and looked at what was actually being done. I _assumed_ this file would be frequently updated, and thus needed to prevent minor mistakes from non-power users. But that clearly isn't how this setup works.

Anyway, I will make some updates later. But does anyone know if there is a Lua library that doesn't require exclusive access to the file being written to? That way a stream can just stay open and overwrite the contents with every key stroke. Way faster than reopening a file every time. I've never worked with files in Lua, so I don;t know

**Comment by stoatally** [comment]
> I never tested it, so I wanted to have it validated by others before doing so.

A pull request is the place to do this, Taran does not have to accept it.

**Comment by tom-sherman** [comment]
@stoatally +1

Pull requests are the exact place to discuss this sort of thing, this is not an issue :-)
