### ISSUE TITLE
issue：two keyboard mess up

### ISSUE THREAD

**Issue by PotatoJet** [TaranVH/2nd-keyboard#101]
Hello~I use your ALL_MULTIPLE_KEYBOARD_ASSIGNMENTS script,but it often happened that my 1st_keyboard work the same as the 2nd_ keyboard,until I reload the script,everything back to normal.Maybe the script allow a key to pass through unwrapped, which cause big problems with cross-talk.Even if I change F23 to scan code,it still can't work.
Please help me out here,thanks.

![image](https://user-images.githubusercontent.com/25473330/70390780-2f5eef00-1a09-11ea-9238-cd56944393ac.png)

**Comment by Matesaktesak** [comment]
So, you think that the F23 is being kept pressed and so all ongoing keypresses activate macros, right?

**Comment by PotatoJet** [comment]
> So, you think that the F23 is being kept pressed and so all ongoing keypresses activate macros, right?

On the contrary，the F23 is  not being kept pressed and so all my 1st_keyboard ongoing keypresses activate macros.

**Comment by PotatoJet** [comment]
> So, you think that the F23 is being kept pressed and so all ongoing keypresses activate macros, right?
> I have tested all variants below and it all seems to work for me:
> 
> * [ ]  SC06E:: return
> * [ ]  SC06E::return
> * [ ]  F23:: return
> * [ ]  F23::return

Thank you so much,I will have a try.
You are a real gentleman.

**Comment by Matesaktesak** [comment]
![Keyboard run Diagram](https://user-images.githubusercontent.com/46134697/70862326-40dd5500-1f3b-11ea-87e7-e8a523ffd6f7.png)

So if the F23 releases no macros will fire - that means that for your primary keyboard to exec. macros F23 had to stay pressed (not released)

**Comment by PotatoJet** [comment]
> ![Keyboard run Diagram](https://user-images.githubusercontent.com/46134697/70862326-40dd5500-1f3b-11ea-87e7-e8a523ffd6f7.png)
> 
> So if the F23 releases no macros will fire - that means that for your primary keyboard to exec. macros F23 had to stay pressed (not released)
> 
> How do you wrap the hotkeys? Intercept, Lua, Hasu, iCue, Razer? (It shouldn't have any effect on your problem thou)
> 
> And do you use a PS-2 keyboard? I had a lot of problems with AHK interfacing it
> 
> Could you attach your All_asing.ahk (or whatever it's called) file?

Sorry to keep you waiting.
Well,I'm using Intercept and normal keyboard.
It's my script ↓↓↓

![image](https://user-images.githubusercontent.com/25473330/70862480-faf2b200-1f77-11ea-93c6-d5e3c40d45ec.png)

**Comment by PotatoJet** [comment]
> ![Keyboard run Diagram](https://user-images.githubusercontent.com/46134697/70862326-40dd5500-1f3b-11ea-87e7-e8a523ffd6f7.png)
> 
> So if the F23 releases no macros will fire - that means that for your primary keyboard to exec. macros F23 had to stay pressed (not released)
> 
> How do you wrap the hotkeys? Intercept, Lua, Hasu, iCue, Razer? (It shouldn't have any effect on your problem thou)
> 
> And do you use a PS-2 keyboard? I had a lot of problems with AHK interfacing it
> 
> Could you attach your All_asing.ahk (or whatever it's called) file?

Thank you for help.I finally give up using intercept,
I am using AutoHotInterception now.It's not need to wrap keystrokes in keystrokes (No need to use F23 to wrap keys)
https://github.com/evilC/AutoHotInterception

**Comment by Matesaktesak** [comment]
Oh! I haven't seen AutoHotInterception before! It seems quite nice actually!
Wish you luck!

**Comment by PotatoJet** [comment]
> Oh! I haven't seen AutoHotInterception before! It seems quite nice actually!
> Wish you luck!

Yeah,Good Luck!

**Comment by PotatoJet** [comment]
@TaranVH  I am sorry to bother you again.
I am using QMK and "ALL_MULTIPLE_KEYBOARD_ASSIGNMENTS " script now,but the same problem happened again.
Sometimes my 1st_keyboard work the same as the 2nd_ keyboard,until I reload the script,everything back to normal.Maybe the script allow a key to pass through unwrapped, which cause big problems with cross-talk.Even if I change F24 to scan code,it still can't work.
Please help me out here,thanks.
![image](https://user-images.githubusercontent.com/25473330/84513655-58d03e80-acfc-11ea-976d-88605fc1f554.png)

**Comment by PotatoJet** [comment]
@Matesaktesak Good news,my brother.
After several month test,I finally work it out!
Just separate one script into two script,like"1st_keyboard.ahk"、"2nd_keyboard.ahk",then they won't mess up anymore!

**Comment by PotatoJet** [comment]
@Matesaktesak Hello my brohter,are you ok?

**Comment by Matesaktesak** [comment]
I'm doing fine, I have just been idle for a bit
