### ISSUE TITLE
Lua Script stops recognizing keyboard if it gets unplugged & plugged back in

### ISSUE THREAD

**Issue by WesleyM77** [TaranVH/2nd-keyboard#102]
If you have the Lua script bound to one of your keyboards by direct ID (by editing the script itself), and you unplug that keyboard and plug it back in, the script will need restarted to continue working. Is there any way around this?

**Comment by PotatoJet** [comment]
try intecept

**Comment by Matesaktesak** [comment]
@WesleyM77 You really shouldn't be using LuaMacros... Try intercept or ideally the [Hasu converter](https://www.1upkeyboards.com/shop/controllers/usb-to-usb-converter/)

Also, @PotatoJet are you the REAL PotatoJet? And if yes, please do a review of the Z-CAM E2-F8!

**Comment by PotatoJet** [comment]
> @WesleyM77 You really shouldn't be using LuaMacros... Try intercept or ideally the [Hasu converter](https://www.1upkeyboards.com/shop/controllers/usb-to-usb-converter/)
> 
> Also, @PotatoJet are you the REAL PotatoJet? And if yes, please do a review of the Z-CAM E2-F8!

Haha,I'm not PotatoJet,I'm his fan.

**Comment by Matesaktesak** [comment]
> > @WesleyM77 You really shouldn't be using LuaMacros... Try intercept or ideally the [Hasu converter](https://www.1upkeyboards.com/shop/controllers/usb-to-usb-converter/)
> > Also, @PotatoJet are you the REAL PotatoJet? And if yes, please do a review of the Z-CAM E2-F8!
> 
> Haha,I'm not PotatoJet,I'm his fan.

Ok 😂 - I'm sorry for littering this chat

**Comment by PotatoJet** [comment]
> > > @WesleyM77 You really shouldn't be using LuaMacros... Try intercept or ideally the [Hasu converter](https://www.1upkeyboards.com/shop/controllers/usb-to-usb-converter/)
> > > Also, @PotatoJet are you the REAL PotatoJet? And if yes, please do a review of the Z-CAM E2-F8!
> > 
> > 
> > Haha,I'm not PotatoJet,I'm his fan.
> 
> Ok 😂 - I'm sorry for littering this chat

It's ok,lol.
If you have time,please help me the #101 issue.
I wonder if you have this problem.Thanks.

**Comment by WesleyM77** [comment]
I no longer have this issue as I have switched to a different macro method. Being that Lua is apparently the wrong way to do this, I'm closing this thread.

**Comment by Rings4** [comment]
> I no longer have this issue as I have switched to a different macro method. Being that Lua is apparently the wrong way to do this, I'm closing this thread.

I've been having this issue for years using intercept. How did you fix this?

**Comment by WesleyM77** [comment]
@Rings4 I switched to using iCue which is an entirely different approach. Best of luck!

**Comment by TaranVH** [comment]
> 



> > I no longer have this issue as I have switched to a different macro method. Being that Lua is apparently the wrong way to do this, I'm closing this thread.
> 
> I've been having this issue for years using intercept. How did you fix this?

You can't AFAIK. Interception has a hard limit of 10 devices. and it "creates" a new device if you unplug and re-plug a keyboard.
This is one reason why I now use the Hasu USB converter method instead.
