### ISSUE TITLE
Unable to figure out how to start intercept keyremap on startup

### ISSUE THREAD

**Issue by Helios5584** [TaranVH/2nd-keyboard#105]
Inside of the intercept program, when you press y to start the keyboard filter there is a line that says "To activate filters on startup, add /apply to the command line". Which command line is the program talking about and how do I apply this change?

Sorry if this is basic, I am not too fluent with command line or modifying programs.

**Comment by TaranVH** [comment]
ummmmmm I'm not sure. watch through the tutorial video again. I worked hard to make sure it shows every single step. I should add the "/apply" to the end of something else that I'm writing in.... somewhere.
I haven't used Interception for years, I'm all about QMK now!

**Comment by Helios5584** [comment]
I actually found what I was looking for in your "Additional Resources" Section at the bottom of README.md in "2nd-keyboard". The "geoffff's follow-up post" contains a custom vbs file called "start-intercept.vbs" which you can place in the Windows Programs Startup folder to start the program without having the terminal come up. I haven't tried it on my setup yet, so I don't know if it works, however this is exactly what I was looking for.
