### ISSUE TITLE
Weird box stating key keeps appearing and doesnt go away.

### ISSUE THREAD

**Issue by renux666** [TaranVH/2nd-keyboard#112]
![weirdbox](https://user-images.githubusercontent.com/63678142/79284132-acb3d800-7eb1-11ea-845f-1c915455a569.JPG)

The image attached is the weird box that appears above everything else on my screen whenever I use a macro. This is extremely frustrating as it blocks out the media I'm working with. Does anyone know a solution?

**Comment by TaranVH** [comment]
Yeah dude. Those are tooltips. When you put in your real macros, you're supposed to comment them out. As in, put a semicolon in front of them.
Or just delete them.

**Comment by TaranVH** [comment]
Just search your AHK script for "tooltip," and you'll find em!
