### ISSUE TITLE
How to Create layout of Macros  what works only in specific window?

### ISSUE THREAD

**Issue by RadovanFindra** [TaranVH/2nd-keyboard#116]
Hello, 
My idea is: Make something like layers for different programs. 
When i open Photoshop i have layout (a.) what is works only in photoshop.
When I open Premiere I have differen layout (b.) works only in Premiere.
And have layout (c.) what works everywhere.

layout (a.) and (b.) uses same keys with different macros on keys.
layout (c.) unique keys  
It's something like this possible?

**Comment by TaranVH** [comment]
Yes, and I do it all the time.

#IfWinActive ahk_exe Photoshop.exe
;keys go here for only photoshop

#IfWinActive ahk_exe Adobe Premiere Pro.exe
;keys go here for only premiere

#IfWinActive
;keys go here for ALL programs

**Comment by RadovanFindra** [comment]
Thaks for Help.
