### ISSUE TITLE
Persistant [F__]. Tooltips won't dissapear

### ISSUE THREAD

**Issue by GrantMan024** [TaranVH/2nd-keyboard#119]
After following your tutorial exactly. The tooltips displayed after any macro is pressed stay on the screen indefinitely until you press another macro key then it changes to reflect that key press but never goes away.. It makes this system unusable because Having a tooltip stay on your screen all the time is literally undoable for me. I really hope someone has found a fix for this because i really love this system and could get miles of use out of it.
![Capture](https://user-images.githubusercontent.com/46170244/81956520-6a2d0a80-95d9-11ea-89b9-5e692b58ed49.PNG)

**Comment by TaranVH** [comment]
haha, which tutorial did you follow? I'll add this clarification.
You're supposed to comment out the tooltips. Those are just placeholders!
so add a ; in front of them. Or delete them!
glad you're getting into this stuff. Did you take the beginner tutorial?
https://www.autohotkey.com/docs/Tutorial.htm
There are some scripting fundamentals that you should know before you go
much further. Commenting stuff out is so fundamental, I hadn't thought to
make a special mention of it!

**Comment by GrantMan024** [comment]
@TaranVH  Thank you so much for your help. I thought I was out of luck on this one. Here's the link to the video.
https://www.youtube.com/watch?v=y3e_ri-vOIo

So excited to dive deeper into this and really make some magic happen.

Also thank you so much for taking the time to do all of this. this is an amazing thing everyone should know about and I'm glad you've made it a goal of yours to spread the word. Much luck with all your current and future ventures!

**Comment by GrantMan024** [comment]
so @TaranVH im still confused on what to remove. every instance of tooltips? because when i goto letter r or something, in the code there is empty space next to it. is there a specific line that creates a tooltip for every key?

**Comment by TaranVH** [comment]
again, it's important to take the AHK tutorial before you delve into this!
I'm pretty sure it tells you that when you have multiple lines with blank
space after the :: that it uses the command from the NEXT line until it
DOES find one with info next to the ::

**Comment by GrantMan024** [comment]
Got it got it. I should have watched this in the begining... Thanks for the help!

**Comment by amzawisza** [comment]
I personally like the tooltip so I just adjust it so that it fires a script with the input of the key(s) pressed that creates the tooltip then times out the tooltip after a second or two, that fires right after the hotkey action.
