### ISSUE TITLE
problem with multiple lines

### ISSUE THREAD

**Issue by joran05j** [TaranVH/2nd-keyboard#120]
i tried to run my script (in description) but when i push a assigned key it automaticly launches the other macros as well. the keypressed document works just fine. i have not too much experience with autohotkey but i have been programming with it for a few hours. i do like programming arduino and have more than 100 hours arduino experience. anyways, nice work and it worked almost perfectly for me. Great work and i love your tutorials on these kind of things.

ps. sorry for my bad english, i am a middle school student in the netherlands

[2nd_keyboard_if_using_luamacros_in_txt.txt](https://github.com/TaranVH/2nd-keyboard/files/4643579/2nd_keyboard_if_using_luamacros_in_txt.txt)

**Comment by TaranVH** [comment]
you probably didn't end your key assignment with a RETURN.
You really need to take the tutorial before you mess with this stuff:
https://www.autohotkey.com/docs/Tutorial.htm

**Comment by joran05j** [comment]
i did use return before but do i have to use it on every line?

**Comment by joran05j** [comment]
i had already done that but it didn't help

**Comment by joran05j** [comment]
i know what is the problem now, i didn't put the multiple lines for a launch inbetween curly brackets
