### ISSUE TITLE
Keystroke_Viz isn't working

### ISSUE THREAD

**Issue by George4All** [TaranVH/2nd-keyboard#130]
I recently started getting into using AHK and since I show some people how to start video editing, Keystroke_Viz was perfect for me. Unfortunatley it isn't working, no matter what I do, the red logo
![image](https://user-images.githubusercontent.com/67630512/86104725-badfc080-babe-11ea-8e72-92366f059c1b.png) is appearing in the taskbar, but nothing else. I tried compiling the script, moving it to C:/AHK instead of C:\AHK\2nd-keyboard\Taran's_Windows_Mods, but nothing worked. I double checked and its not paused or suspended. If anyone can help me I'd really appreciate. Thanks

**Comment by TaranVH** [comment]
did you watch the accompanying video?
https://www.youtube.com/watch?v=gF-f25dRbo8
I hardly even use this script anymore, myself.
It needs a .txt file somewhere to work properly.
And the AHK GUI has always been a serious PITA to use.
I really can't help you beyond that. good luck though!

**Comment by George4All** [comment]
I watched it, that's the video that redirected me here but thank you for finding time to reply to me! You've inspired me to start editing video! Thanks
