### ISSUE TITLE
Make a hex file for NO_REPLUG_ISSUES_with_modifiers

### ISSUE THREAD

**Issue by ellman12** [TaranVH/2nd-keyboard#134]
For the past few hours I have been struggling to make a .hex file for NO_REPLUG_ISSUES_with_modifiers. I finally produced a hex file, but it doesn't work at all. If someone could either help me make one, or make one and commit to the repo for all to use, that would be greatly appreciated!

**Comment by TaranVH** [comment]
what do you mean? they're all here:
https://github.com/TaranVH/2nd-keyboard/tree/master/HASU_USB/NO_REPLUG_ISSUES
https://github.com/TaranVH/2nd-keyboard/blob/master/HASU_USB/NO_REPLUG_ISSUES/F24_Zuk_Hasu.hex

**Comment by ellman12** [comment]
No I meant for no replug with modifiers. There isn't a hex file. I tried making one but it wouldn't work. Ideally, I would like a hex file combining both no replug issues and F24 with modifiers.

https://github.com/TaranVH/2nd-keyboard/tree/master/HASU_USB/NO_REPLUG_ISSUES_with_modifiers

**Comment by TaranVH** [comment]
ah i see. I may be able to make one tonight. no promises!

**Comment by ellman12** [comment]
oh that would be amazing! :)

**Comment by TaranVH** [comment]
well, I tried. but I don't have ubuntu installed, nor the QMK repository
downloaded any longer, on any machine. And it's too much work for me to do
so at this point.
Anyway, what I do to get some of those modifiers back, is this:

https://github.com/TaranVH/2nd-keyboard/blob/master/ALL_MULTIPLE_KEYBOARD_ASSIGNMENTS.ahk#L445

;;Lshift -to-> SC070-International 2 -back-to-> Lshift. This is easier than
having to re-flash the QMK chip...
SC070::Lshift

however, this won't work for ALL of them, as some are only UP events...

what was your issue in creating the hex file? were you able to make a .hex
file, but it just didn't work?

**Comment by ellman12** [comment]
yeah I made it but it didn't work.

in the video I got to here: [.](https://youtu.be/kTXK8kZaZ8c?t=580) This is probably where I messed up. The hex I made flashed but it acted like a normal keyboard I think. I.e., no AutoHotkey stuff was working on it. Idk if no_replug would fix it but sometimes after waking up my PC from sleep the Hasu/keyboard stops receiving power or something. Thus requiring a replug.

**Comment by ellman12** [comment]
;;Lshift -to-> SC070-International 2 -back-to-> Lshift. This is easier than
having to re-flash the QMK chip...
SC070::Lshift

what would this do? I think I had this in my code at one point but removed it cuz I don't think it did anything

**Comment by dantheawesomebam** [comment]
Here you go (you just have to change the extension back from "*.txt" to "*.hex" (I had to change it because no hex-files can be uploaded currently on Git)

Visit https://geekhack.org/index.php?topic=69169.msg3100490#msg3100490 for more info.

PS. All without guarantee, but works for me ;)
[F22_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039587/F22_usb_usb_unimap.txt)
[F23_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039588/F23_usb_usb_unimap.txt)
[F24_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039589/F24_usb_usb_unimap.txt)

**Comment by PotatoJet** [comment]
> replug

Hello my friend,have you solved the replug issue？It makes me crazy！Please help me solve the replug issue.

**Comment by PotatoJet** [comment]
> Holy crap I forgot about this lmao. Thank you for doing that. Probably won't actually end up using those because I recently got a Stream Deck XL to replace my 2nd keyboard but I appreciate you doing that regardless. If they aren't already in the repo I think someone should add them.

> replug

Hello my friend,have you solved the replug issue？It makes me crazy！Please help me solve the replug issue.

**Comment by PotatoJet** [comment]
> Here you go (you just have to change the extension back from "_.txt" to "_.hex" (I had to change it because no hex-files can be uploaded currently on Git)
> 
> Visit https://geekhack.org/index.php?topic=69169.msg3100490#msg3100490 for more info.
> 
> PS. All without guarantee, but works for me ;) [F22_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039587/F22_usb_usb_unimap.txt) [F23_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039588/F23_usb_usb_unimap.txt) [F24_usb_usb_unimap.txt](https://github.com/TaranVH/2nd-keyboard/files/8039589/F24_usb_usb_unimap.txt)

Hello,do you mean just use your hex file and plug it directly into the computer,then the replug issue will be solved?

**Comment by dantheawesomebam** [comment]
Hi PotatoJet,
yes, that's how it works for me. Just make sure to grab the right hex-file (e.g. F23) and use this one instead of Taran's. Should work.
Take care mate

**Comment by PotatoJet** [comment]
> Hi PotatoJet, yes, that's how it works for me. Just make sure to grab the right hex-file (e.g. F23) and use this one instead of Taran's. Should work. Take care mate

Hello my dude,I finally work it out！
The fake U2U cause the replug issue,so I buy a new one，it works fine now！
Do remember use Zuk's hex！
