### ISSUE TITLE
Corsair iCue eating all keystrokes

### ISSUE THREAD

**Issue by WesleyM77** [TaranVH/2nd-keyboard#135]
I downloaded the FileMatrix Tester found here: https://www.sprintek.com/en/support/Downloads.aspx
and I don't see any keystrokes when typing on my second keyboard. I've restarted iCue and check for updates and it's all kosher. I restarted my AHK script a few times and it's fine too. It looks like iCue is eating my keystrokes. I updated windows last night too, so it could be an issue there. Anyone else having this issue?

**Comment by TaranVH** [comment]
is your second keyboard a Corsair one?
I deliberately don't use Corsair for the 2nd keyboard, to avoid this
potential issue.

**Comment by WesleyM77** [comment]
@TaranVH Yes, my second is a corsair. the iCue workflow was the best solution for me. This is the first time I've had this issue of iCue eating keystokes. I'll try a restart towards the end of the workday, being that the second keyboard is for my work laptop.

**Comment by WesleyM77** [comment]
My main keyboard is not though, so I only have one corsair board connected. If corsair is a bad choice, you might want to update your recommendations google doc found in the README.

**Comment by TaranVH** [comment]
oh, I see. I don't use Corsair for my 2nd keyboard, because my primary
keyboard is Corsair.
Using corsair for JUST the 2nd keyboard should be fine. At least, it was
the last time I did that!
Unfortunately, you're on your own for figuring out how to fix
your strange issue. Good luck!

**Comment by WesleyM77** [comment]
Appreciate the words of encouragement. I'll update and close this should I figure out the issue so it's archived. If anyone else is having the same issue and has discovered anything, please comment.

**Comment by WesleyM77** [comment]
Finally got a chance to restart my machine and it's working again. Forgetting the most basic troubleshooting step when you're a web developer is kinda embarrassing...

**Comment by TaranVH** [comment]
We've all done it.....
glad you're back up and running :)
