### ISSUE TITLE
Idea: Greek keyboard for more keys to assign shortcuts to

### ISSUE THREAD

**Issue by Jonta** [TaranVH/2nd-keyboard#138]
In your video from 4 months ago, "Premiere's EXCALIBUR extension - is it good? Kinda." - https://www.youtube.com/watch?v=jQmkyM4CCy4 (24min), you mentioned running out of keys to assign, and that you wanted 10k F-keys (F1, F2, F3, … F10k)

I don't have access to Adobe software right now, so I can't test whether they allow special characters as parts of shortcuts

Other keywords: Cyrillic, Russian, Japanese, Chinese, Hindi, Punjabi, Arabic

Lua macros, as mentioned by Tom Scott in "The Art of the Bodge: How I Made The Emoji Keyboard" - https://www.youtube.com/watch?v=lIFE7h3m40U (17min) you've explained why you don't use, but I forget, and that info should be outside a video as well. (Also, [searching this repo for "Lua"](https://github.com/TaranVH/2nd-keyboard/search?q=lua) brings up results suggesting you _are_ using it, confusing me even more)

**Comment by TaranVH** [comment]
I did use luamacros, but currently still use the Hasu usb to usb keyboard converter.

**Comment by Jonta** [comment]
Ah yes, it's in the readme under "[…] these are all the methods that I know of"

E.g. Greek keyboard not an option then?

**Comment by TaranVH** [comment]
In my (limited) experience, it doesn't work. I believe I'd need to change
the language of the entire program first.
But if you have better luck, let me know!

**Comment by Jonta** [comment]
Research notes:
- Tools: `xev`, `evtest`
- Keycodes v. keysymbols v. character codes v. scan codes
- YouTube - Computerphile - What happens when I press a key? - 12 min - https://www.youtube.com/watch?v=ewE8b7zzej0

Ben Eater-videos (consecutive, oldest first):
| Title                                       | Link                                        | Minutes |
| :------------------------------------------ | :------------------------------------------ | ------: |
| So how does a PS/2 keyboard interface work? | https://www.youtube.com/watch?v=7aXbh9VUB3U |      33 |
| Keyboard interface hardware                 | https://www.youtube.com/watch?v=w1SB9Ry8_Jg |      28 |
| Keyboard interface software                 | https://www.youtube.com/watch?v=dL0GO9SeBh0 |      20 |
| How does a USB keyboard work?               | https://www.youtube.com/watch?v=wdgULBpRoXk |      34 |
