### ISSUE TITLE
Add USB Usage ID

### ISSUE THREAD

**Issue by quadrinex** [TaranVH/2nd-keyboard#179]
Hello, can you add the [usage id (page 53)](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf) to your [spreadsheet](https://docs.google.com/spreadsheets/d/1GSj0gKDxyWAecB3SIyEZ2ssPETZkkxn67gdIwL1zFUs). 
Thanks

**Comment by quadrinex** [comment]
I did it myself finally, i give you [the file](https://docs.google.com/spreadsheets/d/1QhymDjomIAUJil-x64QgSbSKqdsHIvU9TIjiKuE5_Xw/edit?usp=sharing) with the usage id
And i also added changed the usage id link so it go to the good page.

**Comment by TaranVH** [comment]
I don't see a difference between these sheets?

**Comment by TaranVH** [comment]
sorry, was looking at the wrong sheet.
I've added it :)

**Comment by quadrinex** [comment]
thanks

**Comment by quadrinex** [comment]
oh and for the link at the top left i recommend using this link because it go to the page 53 https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf#page=53

**Comment by TaranVH** [comment]
Done. But that link was actually redundant. it's only over the columns now.

**Comment by quadrinex** [comment]
Ok good
