### ISSUE TITLE
Where is the ahk from the video?`

### ISSUE THREAD

**Issue by harsh5559** [TaranVH/2nd-keyboard#22]
both Taran's Lua code and autohotkeys code is missing for me, I'm trying to make a soundboard keyboard kind of thing where every key types out a line of words. Where is this legendary Transitions, Effects, and 2nd keyboard functions.ahk that im supposed to be using?

**Comment by TaranVH** [comment]
BRO. THEY ARE NOW CALLED:

SECOND KEYBOARD Premiere functions in AutoHotKey.ahk

AND ALSO

SECOND KEYBOARD script for LUA MACROS.lua

YEAH MAN.
