### ISSUE TITLE
[suggestion] finaly LUA macros is not the best idea

### ISSUE THREAD

**Issue by zurbo** [TaranVH/2nd-keyboard#24]
If i understand right you have used LUA macros because AutoHotkeys can not make the difference between the two connected keyboards... Buuuuut I think it can with this addon: https://autohotkey.com/board/topic/38015-ahkhid-an-ahk-implementation-of-the-hid-functions/

This will solve problems like:
-Long write/read on a file
-Only one program is running in background
-Path to the output file

**Comment by Fjolnir-Dvorak** [comment]
As far as I can judge the plugin you mentioned is not capable of dropping the actual key you pressed which I suppose this program is capable to do.

**Comment by TaranVH** [comment]
Indeed. I already had looked into AHKID, it does not BLOCK the keystroke.
HID macros does block keystrokes, but it is a pain to set up each key induvidually.
LuaMacros blocks keystrokes, but sometimes fails to work.
Intercept.exe works the best, the only trouble being that sometimes OTHER keyboards are blocked for no reason.
