### ISSUE TITLE
KeypressOSD Cuts Off

### ISSUE THREAD

**Issue by EposVox** [TaranVH/2nd-keyboard#28]
On my screen, letters are very off-center and any lengthy press (i.e. "LButton) gets completely cut off.
I feel like the code for this UI should be obvious, but nothing I'm changing seems to adjust or fit the black bar background.

I tried adjusting "Gui, Margin, 0, 0" & "Gui, Add, Text, vHotkeyText Center y50" (y50) and neight of those did anything.

_Also if you press a Numpad number more than once it deletes the original number post and starts saying "Numpad [number]" again._

Grabbed a better photo of the alignment issue with my phone.

What do I need to change for this?

![1](https://cloud.githubusercontent.com/assets/18689681/23189058/1eadc8b2-f85f-11e6-81b3-06afdeedd38a.png)
![2017-02-21 17 55 43](https://cloud.githubusercontent.com/assets/18689681/23189199/d4698326-f85f-11e6-8e8f-3e1d24afb6d8.jpg)

**Comment by vuribe1221** [comment]
I created a Pull request yesterday that addresses these issues and adds many features.
The pull request is called **Vuribe1221 MegaPatch** and you should be able to see that changes and download the script. If not I have attached it here. 

You may need to change **fontCharWidth** which will cutoff letter or create extra blank spaces at the end of the message if the number is too small or large respectively.

[KeypressOSDVuribe1221.zip](https://github.com/TaranVH/2nd-keyboard/files/1318543/KeypressOSDVuribe1221.zip)

**Comment by EposVox** [comment]
![image](https://user-images.githubusercontent.com/18689681/32356128-6e4ea068-c009-11e7-827e-f5465569b72d.png)
Hey! Sorry for not seeing this - I got your YouTube message. The "Font Char Width" edit works great for that cutoff, but I now have a vertical cutoff issue (possibly caused by Windows scaling? I'm at 200%) and I'm not sure which variable I should change for that.
Amd I being dumb? lol

**Comment by vuribe1221** [comment]
I found that the screen height was a limitation set by the gui window. I have changed some of the settings slightly and made it easier to use please try the attached script and modify the 'windowHeight' variable as necessary.

remove the '.txt' at the end of the file
[KeypressOSD.ahk.txt](https://github.com/TaranVH/2nd-keyboard/files/1442186/KeypressOSD.ahk.txt)

If this works for you then I will ask that you close this bug and I will merge these changes with the master branch.

**Comment by EposVox** [comment]
Perfect!!!
