### ISSUE TITLE
Autohotkey script with lua macros

### ISSUE THREAD

**Issue by TobyForbes** [TaranVH/2nd-keyboard#31]
The lua macros side of things seems to be working fine (except for the non US layout of my keyboard) but the autohotkey side of things just gives me this error: 
![image](https://user-images.githubusercontent.com/8331347/29358437-55d4bad4-827b-11e7-8d3c-0cf14dad1646.png)

It is most likely because I did something wrong but I would like to know how to fix it!

I know Teran recomended switching to another program in another thread although I beleive that you require admin rights for it which I do not have on my computer.

**Comment by TaranVH** [comment]
show me your recallTransition() function. I bet you don't have a parameter in the ().

Also, that function is absolutely terrible anyway... it never worked properly. If you can't get THIS to work, there's no way you'll get recallTransition() to work.

**Comment by barneybear2002** [comment]
Thank you, 
I ended up deleting most of the code and rewriting it because I wanted it for coding instead anyways.
