### ISSUE TITLE
Issues with the 2nd keyboard

### ISSUE THREAD

**Issue by Rogziel0013** [TaranVH/2nd-keyboard#46]
Hello,

As soon as I use my 2nd keyboard (after starting intercept.exe and the .ahk script), I can't use my 1st keyboard anymore, because it does the same functions as the 2nd keyboard, including the macros. Basically, it's as if I have two "2nd" keyboards, and no "1st" keyboard... 

Thanks!

**Comment by Rogziel0013** [comment]
Here are the .ahk file and the .ini file, in case that helps:

**********************************************

#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
#SingleInstance force
#if (getKeyState("F23", "P"))
F23::return
a::^f1
return
9::msgbox, This is a test
w::msgbox, you pressed %A_thishotkey% on the extra keyboard
e::tooltip, you pressed %A_thishotkey% on the extra keyboard
r::SoundBeep, 1000, 500
return
#if
;Done with F23

**********************************************
[Escape -> RELEASE F23]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1,0,0
combo=6E,0,1

[f1]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3b,0,0
combo=6E,0,0|3b,0,0|3b,0,1|6E,0,1
[f2]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3c,0,0
combo=6E,0,0|3c,0,0|3c,0,1|6E,0,1
[f3]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3d,0,0
combo=6E,0,0|3d,0,0|3d,0,1|6E,0,1
[f4]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3e,0,0
combo=6E,0,0|3e,0,0|3e,0,1|6E,0,1
[f5]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3f,0,0
combo=6E,0,0|3f,0,0|3f,0,1|6E,0,1
[f6]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=40,0,0
combo=6E,0,0|40,0,0|40,0,1|6E,0,1
[f7]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=41,0,0
combo=6E,0,0|41,0,0|41,0,1|6E,0,1
[f8]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=42,0,0
combo=6E,0,0|42,0,0|42,0,1|6E,0,1
[f9]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=43,0,0
combo=6E,0,0|43,0,0|43,0,1|6E,0,1
[f10]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=44,0,0
combo=6E,0,0|44,0,0|44,0,1|6E,0,1
[f11]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=57,0,0
combo=6E,0,0|57,0,0|57,0,1|6E,0,1
[f12]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=58,0,0
combo=6E,0,0|58,0,0|58,0,1|6E,0,1

; [f6]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=40,0,0
; combo=290,0,0|290,0,1
; [f7]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=41,0,0
; combo=d0,0,0|d0,0,1
; [f8]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=42,0,0
; combo=e0,0,0|e0,0,1
; [f9]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=43,0,0
; combo=f0,0,0|f0,0,1
; [f10]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=44,0,0
; combo=100,0,0|100,0,1
; [f11]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=57,0,0
; combo=130,0,0|130,0,1
; [f12 - needs fixing]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=6E,0,0
; combo=390,0,0|390,0,1




[tilde]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=29,0,0
combo=6E,0,0|29,0,0|29,0,1|6E,0,1
[1]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2,0,0
combo=6E,0,0|2,0,0|2,0,1|6E,0,1
[2]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3,0,0
combo=6E,0,0|3,0,0|3,0,1|6E,0,1
[3]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4,0,0
combo=6E,0,0|4,0,0|4,0,1|6E,0,1
[4]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=5,0,0
combo=6E,0,0|5,0,0|5,0,1|6E,0,1
[5]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=6,0,0
combo=6E,0,0|6,0,0|6,0,1|6E,0,1
[6]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=7,0,0
combo=6E,0,0|7,0,0|7,0,1|6E,0,1
[7]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=8,0,0
combo=6E,0,0|8,0,0|8,0,1|6E,0,1
[8]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=9,0,0
combo=6E,0,0|9,0,0|9,0,1|6E,0,1
[9]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=a,0,0
combo=6E,0,0|a,0,0|a,0,1|6E,0,1
[0]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=b,0,0
combo=6E,0,0|b,0,0|b,0,1|6E,0,1
[minus]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=c,0,0
combo=6E,0,0|c,0,0|c,0,1|6E,0,1
[equals]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=d,0,0
combo=6E,0,0|d,0,0|d,0,1|6E,0,1
[backspace]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=e,0,0
combo=6E,0,0|e,0,0|e,0,1|6E,0,1

[tab]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=f,0,0
combo=6E,0,0|f,0,0|f,0,1|6E,0,1
[q]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=10,0,0
combo=6E,0,0|10,0,0|10,0,1|6E,0,1
[w]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=11,0,0
combo=6E,0,0|11,0,0|11,0,1|6E,0,1
[e]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=12,0,0
combo=6E,0,0|12,0,0|12,0,1|6E,0,1
[r]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=13,0,0
combo=6E,0,0|13,0,0|13,0,1|6E,0,1
[t]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=14,0,0
combo=6E,0,0|14,0,0|14,0,1|6E,0,1
[y]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=15,0,0
combo=6E,0,0|15,0,0|15,0,1|6E,0,1
[u]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=16,0,0
combo=6E,0,0|16,0,0|16,0,1|6E,0,1
[i]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=17,0,0
combo=6E,0,0|17,0,0|17,0,1|6E,0,1
[o]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=18,0,0
combo=6E,0,0|18,0,0|18,0,1|6E,0,1
[p]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=19,0,0
combo=6E,0,0|19,0,0|19,0,1|6E,0,1
[leftbracket]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1a,0,0
combo=6E,0,0|1a,0,0|1a,0,1|6E,0,1
[rightbracket]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1b,0,0
combo=6E,0,0|1b,0,0|1b,0,1|6E,0,1
[backslash]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2b,0,0
combo=6E,0,0|2b,0,0|2b,0,1|6E,0,1


[caps lock]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=3a,0,0
combo=6E,0,0|3a,0,0|3a,0,1|6E,0,1
[a]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1e,0,0
combo=6E,0,0|1e,0,0|1e,0,1|6E,0,1
[s]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1f,0,0
combo=6E,0,0|1f,0,0|1f,0,1|6E,0,1
[d]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=20,0,0
combo=6E,0,0|20,0,0|20,0,1|6E,0,1
[f]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=21,0,0
combo=6E,0,0|21,0,0|21,0,1|6E,0,1
[g]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=22,0,0
combo=6E,0,0|22,0,0|22,0,1|6E,0,1
[h]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=23,0,0
combo=6E,0,0|23,0,0|23,0,1|6E,0,1
[j]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=24,0,0
combo=6E,0,0|24,0,0|24,0,1|6E,0,1
[k]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=25,0,0
combo=6E,0,0|25,0,0|25,0,1|6E,0,1
[l]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=26,0,0
combo=6E,0,0|26,0,0|26,0,1|6E,0,1
[semicolon]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=27,0,0
combo=6E,0,0|27,0,0|27,0,1|6E,0,1
[singlequote]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=28,0,0
combo=6E,0,0|28,0,0|28,0,1|6E,0,1
[enter]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1c,0,0
combo=6E,0,0|1c,0,0|1c,0,1|6E,0,1


; [leftShift]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=2a,0,0
; combo=6E,0,0|60,0,0|60,0,1|6E,0,1

[z]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2c,0,0
combo=6E,0,0|2c,0,0|2c,0,1|6E,0,1
[x]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2d,0,0
combo=6E,0,0|2d,0,0|2d,0,1|6E,0,1
[c]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2e,0,0
combo=6E,0,0|2e,0,0|2e,0,1|6E,0,1
[v]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=2f,0,0
combo=6E,0,0|2f,0,0|2f,0,1|6E,0,1
[b]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=30,0,0
combo=6E,0,0|30,0,0|30,0,1|6E,0,1
[n]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=31,0,0
combo=6E,0,0|31,0,0|31,0,1|6E,0,1
[m]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=32,0,0
combo=6E,0,0|32,0,0|32,0,1|6E,0,1
[comma]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=33,0,0
combo=6E,0,0|33,0,0|33,0,1|6E,0,1
[period]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=34,0,0
combo=6E,0,0|34,0,0|34,0,1|6E,0,1
[forwardSlash]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=35,0,0
combo=6E,0,0|35,0,0|35,0,1|6E,0,1
; [rightShift]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=36,0,0
; combo=6E,0,0|61,0,0|61,0,1|6E,0,1


; [leftCtrl]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=1d,0,0
; combo=6E,0,0|62,0,0|62,0,1|6E,0,1
[leftWin]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=5b,0,2
combo=6E,0,0|63,0,0|63,0,1|6E,0,1
; [leftAlt]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=38,0,0
; combo=6E,0,0|64,0,0|64,0,1|6E,0,1

[spacebar]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=39,0,0
combo=6E,0,0|39,0,0|39,0,1|6E,0,1

[rightAlt TEST]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=38,0,2
combo=6E,0,0|65,0,0|65,0,1|6E,0,1
[rightWin]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=5c,0,2
combo=6E,0,0|66,0,0|66,0,1|6E,0,1

[appskey to scancode 62]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=5d,0,2
combo=6E,0,0|62,0,0|62,0,1|6E,0,1+

[appskey up blocker]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=5d,0,3
combo=

; [rightCtrl]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=1d,0,2
; combo=6E,0,0|67,0,0|67,0,1|6E,0,1

[rightCtrl]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1d,0,2
combo=6E,0,0|1d,0,2|1d,0,3|6E,0,1



[num0]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=52,0,0
combo=6E,0,0|52,0,0|52,0,1|6E,0,1
[num1]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4f,0,0
combo=6E,0,0|4f,0,0|4f,0,1|6E,0,1
[num2]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=50,0,0
combo=6E,0,0|50,0,0|50,0,1|6E,0,1
[num3]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=51,0,0
combo=6E,0,0|51,0,0|51,0,1|6E,0,1
[num4]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4b,0,0
combo=6E,0,0|4b,0,0|4b,0,1|6E,0,1

; [num5]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,0
; combo=6E,0,0|4c,0,0|4c,0,1|6E,0,1

;the code below changes numpad5 into a SHIFT, but does NOT use F23, which is bad, since any OTHEr key that you press will now just act like it is on the primary keyboard. You must add F23 NOW, not after.
; [num5 down]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,0
; combo=2a,0,0
; [num5 up]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,1
; combo=2a,0,1

;The code below is ALSO annoying, because SHIFT acts weirdly on the numpad, using (for example) NUMPADEND rather than the more predictable SHIFT NUMPAD1
; [num5 down changed to shift, WITH f23 down]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,0
; combo=6E,0,0|2a,0,0
; [num5 up changed to shift, WITH f23 up]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,1
; combo=2a,0,1|6E,0,1

[num5 down changed to ctrl, WITH f23 down]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4c,0,0
combo=6E,0,0|1d,0,0
[num5 up changed to ctrl, WITH f23 up]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4c,0,1
combo=1d,0,1|6E,0,1

; 1d,0,0 ;<-this is left CTRL
; 2a,0,0 ;<-this is left shift

;;original code above ^^
; [num5]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=4c,0,0
; combo=2a,0,0
;num5 has been modified so that the key acts as a SHIFT instead. tee hee!!


[num6]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4d,0,0
combo=6E,0,0|4d,0,0|4d,0,1|6E,0,1
[num7]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=47,0,0
combo=6E,0,0|47,0,0|47,0,1|6E,0,1
[num8]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=48,0,0
combo=6E,0,0|48,0,0|48,0,1|6E,0,1
[num9]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=49,0,0
combo=6E,0,0|49,0,0|49,0,1|6E,0,1
[numLock]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=45,0,0
combo=6E,0,0|45,0,0|45,0,1|6E,0,1
[num/]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=35,0,2
combo=6E,0,0|35,0,2|35,0,3|6E,0,1
[num*]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=37,0,0
combo=6E,0,0|37,0,0|37,0,1|6E,0,1
[num-]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4a,0,0
combo=6E,0,0|4a,0,0|4a,0,1|6E,0,1
[num+]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4e,0,0
combo=6E,0,0|4e,0,0|4e,0,1|6E,0,1
[numpad enter]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=1c,0,2
combo=6E,0,0|1c,0,2|1c,0,3|6E,0,1
[num.]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=53,0,0
combo=6E,0,0|53,0,0|53,0,1|6E,0,1



[printscreen MAYBE]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=37,0,2
combo=6E,0,0|37,0,2|37,0,3|6E,0,1
[printscreen MAYBE]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=37,0,2
combo=6E,0,0|37,0,2|37,0,3|6E,0,1
; [scroll lock MAYBE]
; device=HID\VID_045E&PID_00DD&REV_0173&MI_00
; trigger=46,0,0
; combo=6E,0,0|46,0,0|46,0,1|6E,0,1
[scroll lock to 61]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=46,0,0
combo=6E,0,0|61,0,0|61,0,1|6E,0,1

[scroll lock UP]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=46,0,1
combo=
;remapped to scan code 61.



[insert]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=52,0,2
combo=6E,0,0|52,0,2|52,0,3|6E,0,1|
[home]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=47,0,2
combo=6E,0,0|47,0,2|47,0,3|6E,0,1
[pageup]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=49,0,2
combo=6E,0,0|49,0,2|49,0,3|6E,0,1
[delete]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=53,0,2
combo=6E,0,0|53,0,2|53,0,3|6E,0,1
[end]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4f,0,2
combo=6E,0,0|4f,0,2|4f,0,3|6E,0,1
[pagedown]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=51,0,2
combo=6E,0,0|51,0,2|51,0,3|6E,0,1


[up]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=48,0,2
combo=6E,0,0|48,0,2|48,0,3|6E,0,1
[left]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4b,0,2
combo=6E,0,0|4b,0,2|4b,0,3|6E,0,1
[down]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=50,0,2
combo=6E,0,0|50,0,2|50,0,3|6E,0,1
[right]
device=HID\VID_045E&PID_00DD&REV_0173&MI_00
trigger=4d,0,2
combo=6E,0,0|4d,0,2|4d,0,3|6E,0,1

**Comment by TaranVH** [comment]
code looks good...
The only thing I can think of is...
Are both of your keyboards the same model?
Interception can't tell the difference between USB ports. You gotta use different models for each keyboard.

**Comment by Rogziel0013** [comment]
Thanks for the reply!

It's 2 different models:

Main: Logitech G610
2nd: Microsoft Comfort Curve 2000

I actually got both keyboards to work separately yesterday for as many keystrokes as I wanted with the FULL extra keyboard.ahk file, but when I changed a line in the .ahk file (such as "a::^f1"), it worked on the 2nd keyboard, where an "a" stroke on the second keyboard did "Ctrl+F1", but then the 1st keyboard was recognized as the 2nd keyboard until I turned off the script, regardless of which key I pressed.

Maybe I didn't write the line properly? Or could the USB ports somehow be linked?

Thanks again!

**Comment by TaranVH** [comment]
oh my goodness, wait a minute.
You've got extra RETURNs in there.
Get rid of those!!
Take the AHK beginner's tutorial - otherwise, you're playing with fire.
You can only do that if your key assignment is on more than one line.
a::
msgbox, hello
msgbox, world
return

**Comment by Rogziel0013** [comment]
I took out the extra returns (I forgot that I had tried a few things and didn't tidy up afterwards),m but I had the same problem. So I read up a bit more about Autohotkey, and then I found what worked:

a::send +{F1}
^a::send +{F2}
^s::send ^{F2}

rather than this: 

a:: +F1
^a:: +F2
^s:: ^F2

So thanks for the help, I appreciate it!
