### ISSUE TITLE
Hard to Navagate Repo

### ISSUE THREAD

**Issue by Griffdith** [TaranVH/2nd-keyboard#52]
Could you either use diffrent branchs or have seperate repo for each project? As it is getting hard to work out the each folder is for.

**Comment by TaranVH** [comment]
"Each project..." what do you define a project as?
All this code is what runs on my computer at all times.
You can always start from here:
https://github.com/TaranVH/2nd-keyboard/blob/master/FYI/tarans%20startup%20folder%20DEC%202017.png

I still need to do a proper readme and stuff... but basically, you should be glad that any of this code is public at all. Most people don't share their working scripts.
I had to figure all this stuff out from nothing. I know it's pretty damn disorganized, but at least it's there!

**Comment by Griffdith** [comment]
Like, Luamaros/AutoHotKey integration as one. Interception/AutoHotKey, as another, like that. But what you said, I really don’t care now, thx for public code!

**Comment by TaranVH** [comment]
Yeah, I abandoned luamacros in favor of interception long ago. But all the old code is still available.
