### ISSUE TITLE
intercept.exe can't be set up with mouse

### ISSUE THREAD

**Issue by MPeti1** [TaranVH/2nd-keyboard#59]
If I want to use it to differentiate some buttons which exists both on my keyboard and my mice (e. g. LControl), then I can't do it because the mice does not have a q button

**Comment by TaranVH** [comment]
why do you need a Q button?
Just press A to add a new key
then press the Lcontrol button on your mouse.
then remap it to something.
Also, I never intended this for use with mice. IDK if it works like that.
actually, I just tested it with my mouse's Xbutton1 and Xbutton2... it did not work for me.

**Comment by MPeti1** [comment]
Sorry, now I see it! :D I really shouldn't read manuals if I'm tired
On the other hand it seems that intercept.exe needs interception('s driver) to be installed, so it's not a suitable solution for me :/

**Comment by TaranVH** [comment]
Oh yes, it absolutely needs the interception drivers. There is no better way to make this work.
What mouse do you have? Can you change your mouse's key assignments with software from the manufacturer?

**Comment by MPeti1** [comment]
I have a Trust GXT 180, and it has no setup software

**Comment by MPeti1** [comment]
the final solution for me was LuaMacros. if someone is interested in the solution, it can be found [here](https://1drv.ms/f/s!ArvLKxtjzZnrlqptBIVyTnfJLsIQ4w)
