### ISSUE TITLE
need help with OBS interacting w/ this.

### ISSUE THREAD

**Issue by joshinshaker-vidz** [TaranVH/2nd-keyboard#64]
PLEASE HELP!!!!!!!!!!!!!

This is my issue; my script works with OBS studio when it has focus, but as soon as I click another application, it stops working. here is my keyremap.ini and my AHK.ahk

FYI everything is running as admin.

(yes I know there are some keys in the AHK that are not in keyremap.ini.)

[files.zip](https://github.com/TaranVH/2nd-keyboard/files/2447944/files.zip)

**Comment by joshinshaker-vidz** [comment]
Thank you very much taran! However, I was interested in using AHK due to the flexibility. Do you know how to add delay between keystrokes??? my code is in files.zip

Also, is "   sendinput, ^!p   "  better than " send, {ctrl down}{alt down}a{alt up}{ctrl up}  "???

**Comment by TaranVH** [comment]
I'm not going to do your homework for you, as it were. You've got to put in the work.
Did you take the linked AHK beginner tutorial?
You'd know that
sleep, 50
adds a delay of 50 milliseconds.

usually you want to use
sendinput, ^!p
but sometimes you want to be absolutely certain, which is when i might use
sendinput, {ctrl down}{alt down}a{alt up}{ctrl up}
and sometimes you'd have to parse that out and add little delays
send, {ctrl down}
sleep 10
send, a
sleep 10
send, {ctrl up}
something like that. i think. i didn't check to see if it works.

**Comment by joshinshaker-vidz** [comment]
thank you for your help. I am putting in as much work as I can. I did take the AHK basic tutorial, but I'm 12 and there was a lot I didn't understand. I figured I could ask someone who knows AHK better and understands it for some help. Thanks.

**Comment by joshinshaker-vidz** [comment]
The delay is added (I can see the delay difference of 50 ms between each keystroke) but OBS still isn't catching it.

**Comment by joshinshaker-vidz** [comment]
I figured it out with the help of someone else over on discord. I created another project to share my code on. 
https://github.com/joshinshaker-vidz/streamboard
(I linked to you in the readme)
I plan to update that code over time do do other stuff.
Thank you for your help/inspiring me to do this.
