### ISSUE TITLE
Can't Use AHK #IfWinActive together with #if (getKeyState("F23", "P"))

### ISSUE THREAD

**Issue by bamenny** [TaranVH/2nd-keyboard#65]
Hi,
Sorry if this is not the best place to ask this...

The moment I add the #IfWinActive command to the AHK script,
AHK will accept Hotkey from BOTH keyboards.

`#IfWinActive ahk_exe POWERPNT.EXE`
`m::`
	`send !l`
	`send p`
	`send m`
	`send {Enter}`
	`return`

Tried various combinations to solve this.... any ideas?

**Comment by Wegerich** [comment]
Are you using pretty close to the default code, with a `~F24::` pr similar trigger?

In which case, don't use the # symbol before your ifwinactive as you are starting a new [subroutine] (not sure what it's called in AHK.
You can see an example of my code which works as a global play/pause key.


```
~F23::
FileRead, key, C:\Users\[your username]\Documents\AHK Scripts\2nd-keyboard-master\LUAMACROS\keypressed.txt
If (key = "smample_keyname")
Send {Volume_Down}
else if(key = "numMult")
{
WinGet, WorkingWin ,, A ;Get current window ID
SetTitleMatchMode 2 ; 2: A window's title can contain WinTitle anywhere inside it to be a match. 


IfWinActive, Radio 1,
```

**Comment by TaranVH** [comment]
Wegerich, that code only works for the luamacros method. I believe bamenny is using the interception method.

**Comment by Wegerich** [comment]
Ah my bad, sorry

**Comment by bamenny** [comment]
Yes!!! Thanks! This one actually works great.

m::
	if WinActive("ahk_exe POWERPNT.EXE") 
	{
		send !l
		send p
		send m
	}
	return
