### ISSUE TITLE
What version of Premiere?

### ISSUE THREAD

**Issue by Frasski** [TaranVH/2nd-keyboard#69]
So I updated to Premiere 2019 and none of the Premiere mods work and since I have problems with it crashing and stuff I think I'm gonna downgrade to Premiere 2017 because 2018 I also had problems with the GPU Acceleration. But what version are you using currently and what versions of Premiere are those scripts compatible? Thanks!

**Comment by TaranVH** [comment]
I'm on 2019 but i am still updating everything to make it all compatible again.
Yeah stay on the version you were on. updating is always a dangerous prospect.

**Comment by TaranVH** [comment]
The scripts are currently compatible with 12.0.1

**Comment by Frasski** [comment]
Thank you!
