### ISSUE TITLE
There is no licence

### ISSUE THREAD

**Issue by faissaloo** [TaranVH/2nd-keyboard#7]
The code has no licence, I'd suggest the MIT licence if you don't particularly care how your code is used or GPL if you want anyone who changes your program to make it open source.

**Comment by marksomnian** [comment]
@faissaloo IMO GPL is too restrictive. Maybe [MPL](http://choosealicense.com/licenses/mpl-2.0/)?

**Comment by faissaloo** [comment]
It's up to Taran tbh. I don't particularly care as long as it's some form of libre licence.

**Comment by cjmaxik** [comment]
[WTFPL](http://www.wtfpl.net/) ftw.

**Comment by Amoenus** [comment]
CC0?

**Comment by TaranVH** [comment]
I just want anybody to be able to use this for their own purposes. I dont care how or what they do with it.

unfortunately I can't figure out WHERE the heck I can set the license.

**Comment by cjmaxik** [comment]
@TaranVH, create a file called LICENCE in root directory of your project and copy/paste licence text of your choice.

[WTFPL](http://www.wtfpl.net/txt/copying/) or "DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE" is what you need to.
