### ISSUE TITLE
show "Error:Call to nonexistent function." when run Almost_All_Windows_Functions.ahk

### ISSUE THREAD

**Issue by raining1123** [TaranVH/2nd-keyboard#71]
![image](https://user-images.githubusercontent.com/17892238/48950797-57eb8680-ef77-11e8-925f-1a3109966e19.png)

Error: Call to nonexistent function.
Specifically: Acc_Get("Object","4",0,"ahk id "hWnd)
Line#969:}970:}975:}
1028: Return
1028: JEE_FirefoxFocusTabByName(hWnd,"Linus Media Group Inc. Mail")
1028: Return
1032:{
1033: oAcc:=Acc_Get("Object","4",0,"ahk_id"hWnd)
1034: vRet:=01035: For each, oChild in Acc Children(oAcc)1036: if(oChild. accName(O)=="Browser tabs")
1037:{
1038: oAcc:=Acc Children(oChild)[1], vRet:=11039: Break
1040:}
The program will exit.

**Comment by Z3roCoder** [comment]
This isn't a support forum like he stated so many times before. He's not going to help everyone get it to work, it's his own collection of tools. I doubt he's going to provide support to accommodate every different pc software setup

**Comment by TaranVH** [comment]
This one is a special case, and is my "fault."
That code requires that the ACC library be installed. Most people don't have it.
I don't even remember where I got it from...
https://autohotkey.com/board/topic/77303-acc-library-ahk-l-updated-09272012/
https://github.com/Drugoy/Autohotkey-scripts-.ahk/blob/master/Libraries/Acc.ahk

Anyway, you can pretty much just delete any function that uses ACC stuff.
