### ISSUE TITLE
Key acceptance inconsistencies with OBS [AHK]

### ISSUE THREAD

**Issue by 2tbc1887** [TaranVH/2nd-keyboard#80]
Hey everyone
I'm new to AHK, so I might be doing something wrong but for some reason (with OBS at least, I haven't figured out how to do the other applications I want) there is weird inconsistent acceptance of the hotkeys.

Holding down the button to trigger the bind seems to always make it work, and the keys are always seen by intercept.exe however simply tapping will very rarely work.

Here is my AHK script, there are some duplicates for testing purposes with Voicemod (Which I just can't get to work)
[FULL_extra_keyboard.zip](https://github.com/TaranVH/2nd-keyboard/files/2824306/FULL_extra_keyboard.zip)

**Comment by TaranVH** [comment]
controlsend is screwy.
To get it to work, I had to bring focus to the application first. 
Then return focus to where I was prior to that.
https://github.com/TaranVH/2nd-keyboard/blob/4e687a7b32569ac84a6b12d6b405874a6cf24561/Almost_All_Premiere_Functions.ahk#L1772

**Comment by 2tbc1887** [comment]
It did not seem to work with the window in focus either. I'm probably overlooking something as I'm new to AHK. Sorry!

**Comment by TaranVH** [comment]
You are beyond where I can help you. I know very little about the mysterious controlsend. good luck.

**Comment by roninpawn** [comment]
I think I've figured this OBS/AHK hotkey thing out.

There are two things that ControlSend screws up with OBS. (or that OBS handles poorly from AHK, depending how you want to look at it.) The first is that AHK sends a CTRL key in front of a modifier key, and sometimes OBS reads the CTRL key and doesn't get the rest of it. See here for details:
https://www.autohotkey.com/docs/commands/_MenuMaskKey.htm

The second is that the default timing of the ControlSend event is too quick for OBS to recognize. So sometimes, if you're sending ALT+Numpad4, all OBS gets is the ALT.

So here's the code that fixed it for me:
```
#MenuMaskKey vk07  ;Takes the extra CTRL event out of Alt+ hotkeys.
SetKeyDelay, -1, 50  ;Simulates holding down the key for 50ms.
*!Numpad4::ControlSend, , !{Numpad4}, ahk_class Qt5QWindowIcon
```

I searched and searched and found tons of people having this issue along with me... No one with an explanation or solution. Hopefully this post will put the nail in the coffin on OBS failing to hear hotkeys from AutoHotKey scripts.

**Comment by TaranVH** [comment]
heeyyy, good job! I'm glad you guys are able to figure out these weird
little issues on your own!
I'll keep this thread open in case anyone else has anything more to add.
