### ISSUE TITLE
AHK Compatible Intercept Successor

### ISSUE THREAD

**Issue by FusesFiddlings** [TaranVH/2nd-keyboard#85]
First of all, I would like to thank you for inspiring me to get my own macro keyboard! This is only an issue insofar as I think it is well worth being added to your list of methods. 

I was originally going to use iCue but I happened to want to use both a red macro and brown typing keyboard from Corsair so I had to figure out how to create an independent macro keyboard myself. This is what I found:

https://github.com/evilC/AutoHotInterception

This interceptor is built on top of the Interception driver by Francisco Lopez and allows super easy integration with AutoHotKey. It took me about an hour to setup and is delightful. The only part that was a PITA was figuring out how to run the interceptor installer using an admin command line. In the above repository, the Context Example.ahk file shows just how easily it is implemented. The Monitor.ahk file allows the determination of the device, its VID, and its HID. 

Unlike the Hasu, it doesn't allow manufacturer software to work with the keyboard (tested on a K63). iCue is itself an interceptor and generates an instance of a virtual keyboard when active that works at a lower level than the Interception driver. 

I will see if Corsair creates multiple virtual keyboards in several days when I get in my other keyboard from them.

**Comment by oliver-ni** [comment]
#45

**Comment by FusesFiddlings** [comment]
Thanks! I will close this then.

**Comment by FusesFiddlings** [comment]
Thanks! I will close this then.
