### ISSUE TITLE
Sources for Function key codes.

### ISSUE THREAD

**Issue by InquisitivePuma** [TaranVH/2nd-keyboard#87]
The keycodes used in the keyremap.ini (F24-6E, ect) aren't matching any keymaps I've come across, and there doesn't appear to be a source given for them. Would itbe possible to link either an original source for these codes or a matching keymap?

**Comment by InquisitivePuma** [comment]
https://github.com/TaranVH/2nd-keyboard/blob/master/INFO_and_PROFILES/Table_of_all_scan_codes.xlsx

**Comment by TaranVH** [comment]
I love it when people solve their own problems <3
