### ISSUE TITLE
Keys like Windows, Ctrl, Shift etc. don't work properly

### ISSUE THREAD

**Issue by Jerreu** [TaranVH/2nd-keyboard#88]
Those keys are written to keypressed.txt but the F24 Key is not triggered. When changing the F24 Key to 'b' Shift works, but Win or Ctrl stil won't work. Hence, key combinations, like Shift + s, seem to currently be impossible.

**Comment by TaranVH** [comment]
Are you using luamacros?
Yes, modifier keys were never supported.
You can make LONE modifier keys work, you just have to add them to the .lua script and to the .ahk script.
but shift S or CTRL G will not work.
For that, you'll need to use interception, or QMK.

**Comment by Jerreu** [comment]
Hey Thanks, yeah am using Lua, thanks for the clarification.
