### ISSUE TITLE
KEYSTROKE_VIZ.ahk persistent OSD, doesn't hide after 1500ms

### ISSUE THREAD

**Issue by ertwro** [TaranVH/2nd-keyboard#93]
I love the visualizer. My only problem is it doesn't disappear after it dims. The `timetoshow=1500` is set. I've also tried with "timetohide=1500". Sincerely I don't know why it persists.

**Comment by ertwro** [comment]
No hope of a response. Anyway, cool tool.

**Comment by TaranVH** [comment]
ah sorry. I don't really provide technical support and stuff. also I didn't see this.
Yeah I designed it to be persistent. you can use a timer and gui, hide to make it vanish. something like that. Documentation is here, good luck! https://www.autohotkey.com/docs/commands/Gui.htm

**Comment by ertwro** [comment]
@TaranVH Thank you, you are amazing! I didn't deserve a response yet you gave me a good one that helped me solve my problem 😭 Again I love you your tool. Thanks for sharing.
