### ISSUE TITLE
Help!How I edit script When I add 3rd keyboard using LuaMacros?

### ISSUE THREAD

**Issue by yy353756238** [TaranVH/2nd-keyboard#95]
Dear Taran,I ask for LuaMacros question.When I add 3rd keyboard,how I edit script?I try to change F24 to F23 and keyboardIdentifier,but it's still didn't work(2nd 3rd shouldn't have the same function,but it did)Please help me,thank you so much.

**Comment by TaranVH** [comment]
I've never used Luamacros with a 3rd keyboard. I don't know if it even can do it. You're on your own!
Interception and QMK are known to be able to handle a 3rd, 4th, etc keyboard.

**Comment by yy353756238** [comment]
Thanks Taran，I should use Interception rather than luamacros.I am verry happy that you help me again and again，next time you come to China Hangzhou，I will take you to eat a lot of delicious food and some beautiful place to have fun.------------------ 原始邮件 ------------------
发件人: "TaranVH"<notifications@github.com>
发送时间: 2019年10月9日(星期三) 凌晨0:33
收件人: "TaranVH/2nd-keyboard"<2nd-keyboard@noreply.github.com>;
抄送: "yy353756238"<353756238@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TaranVH/2nd-keyboard] Help!How I edit script When I add 3rdkeyboard using LuaMacros? (#95)



I've never used Luamacros with a 3rd keyboard. I don't know if it even can do it. You're on your own!
 Interception and QMK are known to be able to handle a 3rd, 4th, etc keyboard.
 
&mdash;

**Comment by lal12** [comment]
> Dear Taran,I ask for LuaMacros question.When I add 3rd keyboard,how I edit script?I try to change F24 to F23 and keyboardIdentifier,but it's still didn't work(2nd 3rd shouldn't have the same function,but it did)Please help me,thank you so much.

You could try a tool I developed a while back: https://github.com/lal12/macroMyKBD
It is not well tested, however technically it can do as much keyboards as you like without a problem.

**Comment by MikuGenius** [comment]
> > Dear Taran,I ask for LuaMacros question.When I add 3rd keyboard,how I edit script?I try to change F24 to F23 and keyboardIdentifier,but it's still didn't work(2nd 3rd shouldn't have the same function,but it did)Please help me,thank you so much.
> 
> You could try a tool I developed a while back: https://github.com/lal12/macroMyKBD
> It is not well tested, however technically it can do as much keyboards as you like without a problem.
Thank you,I try to see if it works.

**Comment by MikuGenius** [comment]
> > Dear Taran,I ask for LuaMacros question.When I add 3rd keyboard,how I edit script?I try to change F24 to F23 and keyboardIdentifier,but it's still didn't work(2nd 3rd shouldn't have the same function,but it did)Please help me,thank you so much.
> 
> You could try a tool I developed a while back: https://github.com/lal12/macroMyKBD
> It is not well tested, however technically it can do as much keyboards as you like without a problem.

I hope that you can make a vedio tutorial about how to use it on YOUTUBE,it's difficult for many people to understand.Thank you very much.

**Comment by lal12** [comment]
> I hope that you can make a vedio tutorial about how to use it on YOUTUBE,it's difficult for many people to understand.Thank you very much.

If enough people use it, I probably would improve it and maybe add a little GUI.

**Comment by TaranGenius** [comment]
> > I hope that you can make a vedio tutorial about how to use it on YOUTUBE,it's difficult for many people to understand.Thank you very much.
> 
> If enough people use it, I probably would improve it and maybe add a little GUI.

Thank you for you kind message.I strongly advice you to make a vedio tutorial frist,then billion of people will know it and use it.
