### ISSUE TITLE
How to minimize "intercept.exe" to tray automatically when Windows start?

### ISSUE THREAD

**Issue by TaranGenius** [TaranVH/2nd-keyboard#96]
@TaranVH I promise it's my last question.How to minimize or hide "intercept.exe" window,I want to keep my taskbar clean.I'm very appreciate that you will help me,I'm waiting for your kind message
.
![1](https://user-images.githubusercontent.com/25473330/66691054-7c06a200-ecc6-11e9-926d-f9f6beba9e46.png)

**Comment by TaranVH** [comment]
Haha I have no idea. I know it's annoying. I never bothered to figure out how, because while my PC is still booting up, I can't really open premiere yet anyway.
I think SOMEONE posted a solution SOMEWHERE, probably on this github repo. If you find it, please do post it here!

**Comment by TaranGenius** [comment]
Sorry,I can't understand What does "while my PC is still booting up, I can't really open premiere yet anyway‘’ mean.Yeah,if I find the solution,I will post it here.     Last time you used "intercept.exe",you just leave it's window on taskbar?

**Comment by TaranGenius** [comment]
> Haha I have no idea. I know it's annoying. I never bothered to figure out how, because while my PC is still booting up, I can't really open premiere yet anyway.
> I think SOMEONE posted a solution SOMEWHERE, probably on this github repo. If you find it, please do post it here!

Sorry,I can't understand What does "while my PC is still booting up, I can't really open premiere yet anyway‘’ mean.Yeah,if I find the solution,I will post it here. Last time you used "intercept.exe",you just leave it's window on taskbar?

**Comment by Gum-Joe** [comment]
@TaranGenius Here's some advice from me:
Now I don't know exactly how Intercept.exe is launched on startup, but assuming you're using some sort of `.bat` script to run it on startup via CMD, you can wrap the call to the "intercept.exe" in a Visual Basic File, running CMD with an option to hid itself (e.g. not make a windows and therfore not show up in the taskbar).

Create a file such as `run-intercept.vbs` in your user's startup folder and add these contents:
```vbs
Set oShell = CreateObject("Wscript.Shell") 
Dim strArgs
strArgs = "cmd /c intercept.exe etc"
oShell.Run strArgs, 0, false
```

**Comment by TaranGenius** [comment]
> @TaranGenius Here's some advice from me:
> Now I don't know exactly how Intercept.exe is launched on startup, but assuming you're using some sort of `.bat` script to run it on startup via CMD, you can wrap the call to the "intercept.exe" in a Visual Basic File, running CMD with an option to hide itself (e.g. not make a window and therefore not show up in the taskbar).
> 
> Create a file such as `run-intercept.vbs` in your user's startup folder and add these contents:
> 
> ```vbnet
> Set oShell = CreateObject("Wscript.Shell") 
> Dim strArgs
> strArgs = "cmd /c intercept.exe etc"
> oShell.Run strArgs, 0, false
> ```
> 
> (Of course, change the bit after the `/c` for whatever applies)

OMG,thank you very very much,it works!I really really appreciate you!

**Comment by TaranGenius** [comment]
@TaranVH Thank you anyway,I have found the solution that Gum-Joe told on above line↑↑↑

**Comment by Gum-Joe** [comment]
You're welcome!

**Comment by xAnkur** [comment]
> @TaranGenius Here's some advice from me:
> Now I don't know exactly how Intercept.exe is launched on startup, but assuming you're using some sort of `.bat` script to run it on startup via CMD, you can wrap the call to the "intercept.exe" in a Visual Basic File, running CMD with an option to hide itself (e.g. not make a window and therefore not show up in the taskbar).
> 
> Create a file such as `run-intercept.vbs` in your user's startup folder and add these contents:
> 
> ```vbnet
> Set oShell = CreateObject("Wscript.Shell") 
> Dim strArgs
> strArgs = "cmd /c intercept.exe etc"
> oShell.Run strArgs, 0, false
> ```
> 
> (Of course, change the bit after the `/c` for whatever applies)

HELPPPP PLEASE

**Comment by daominh89** [comment]
> @TaranGenius Here's some advice from me: Now I don't know exactly how Intercept.exe is launched on startup, but assuming you're using some sort of `.bat` script to run it on startup via CMD, you can wrap the call to the "intercept.exe" in a Visual Basic File, running CMD with an option to hide itself (e.g. not make a window and therefore not show up in the taskbar).
> 
> Create a file such as `run-intercept.vbs` in your user's startup folder and add these contents:
> 
> ```vbnet
> Set oShell = CreateObject("Wscript.Shell") 
> Dim strArgs
> strArgs = "cmd /c intercept.exe etc"
> oShell.Run strArgs, 0, false
> ```
> 
> (Of course, change the bit after the `/c` for whatever applies)

@Gum-Joe 
Could you explain more about the line:
`strArgs = "cmd /c intercept.exe etc"`
