### ISSUE TITLE
If someone post Hasu_USB F21.hex here,I even can pay for it!

### ISSUE THREAD

**Issue by TaranGenius** [TaranVH/2nd-keyboard#98]
I have saw the hasu_usb video tutorial,but I still can't figure out how to create F21.hex actually.I'am also a veido editor,I strongly need F21.hex, please help me out here,thanks.

**Comment by TaranVH** [comment]
did you figure out how to create it? Or did you decide to use a super function key for which there is already a hex file?

**Comment by TaranGenius** [comment]
> did you figure out how to create it? Or did you decide to use a super function key for which there is already a hex file?
Well,I'm using a hex file that you already made,and I'm still trying to create a F21.hex(It's a huge PITA to set up for me,lol).If someone post a F21.hex here,it will be fantastic!

Here is a good news,Zucca remake hex file for you,so you  don't need to unplug or replug the HASU Converter anymore after reboot.I advice you to update hex file in GitHub.

Zucca:
https://geekhack.org/index.php?topic=69169.msg2781175#msg2781175
![QQ截图20191105131301](https://user-images.githubusercontent.com/25473330/68180317-393aa000-ffce-11e9-8ecc-cf0becc8bf54.png)

**Comment by TaranGenius** [comment]
Hello Taran,do you decide to update hex file in GitHub?@TaranVH
